# Generated by Django 5.0.2 on 2024-02-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='flag',
            field=models.CharField(default='Flag', max_length=255),
        ),
    ]
