# Generated by Django 5.0.2 on 2024-02-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_callrecording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecording',
            name='recording',
            field=models.FileField(upload_to='call_recordings/'),
        ),
    ]
