# Generated by Django 5.0.2 on 2024-02-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_callrecording_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecording',
            name='recording',
            field=models.FileField(upload_to='static/call_recordings/'),
        ),
    ]
