# Generated by Django 5.0.2 on 2024-02-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_user_call_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='admin_flag',
            field=models.CharField(default='Flag', max_length=255),
        ),
    ]
